GET HTTP://localhost:8081/api/categorias

###

GET HTTP://localhost:8081/api/categorias/2

###

POST HTTP://localhost:8081/api/categorias
Content-Type: application/json

{
    "descricao": "aaaa",
    "observacao": "aaaaaa"
}

###

PUT HTTP://localhost:8081/api/categorias/5
Content-Type: application/json

{
    "descricao": "bbbb",
    "observacao": "bbbbbb"
}

###

DELETE HTTP://localhost:8081/api/categorias/5